# Pod1/pod1-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod1
  template:
    metadata:
      labels:
        app: pod1
    spec:
      containers:
      - name: node-app
        image: leo22002/pod1:latest
        ports:
        - containerPort: 3000
