# pod2/pod2-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod2
  template:
    metadata:
      labels:
        app: pod2
    spec:
      containers:
      - name: node-app
        image: leo22002/pod2:latest
        ports:
        - containerPort: 3000