apiVersion: v1
kind: Service
metadata:
  name: pod2-service
spec:
  selector:
    app: pod2 
  ports:
    - protocol: TCP
      port: 80  # Puerto del Service
      targetPort: 3001  # Puerto del pod
  type: LoadBalancer